/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 car.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.065, 1.154, 2.734]}>
        <mesh geometry={nodes.Circle.geometry} material={materials['donut glaze']} />
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Donut base']} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials['Auto roos']} />
        <mesh geometry={nodes.Circle_3.geometry} material={materials['Auto wit']} />
        <mesh geometry={nodes.Circle_4.geometry} material={materials.ruit} />
        <mesh geometry={nodes.Circle_5.geometry} material={materials.Metaal} />
        <mesh geometry={nodes.Circle_6.geometry} material={materials.lamp} />
        <mesh geometry={nodes.Circle_7.geometry} material={materials.bord} />
        <mesh geometry={nodes.Circle_8.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Circle_9.geometry} material={materials['afdak blauw']} />
        <mesh geometry={nodes.Circle_10.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Circle_11.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Circle_12.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Circle_13.geometry} material={materials['Material.007']} />
      </group>
      <group position={[0, 0.355, 0.705]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials.Banden} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.Metaal} />
      </group>
      <group position={[0, 5.532, 2]}>
        <mesh geometry={nodes.Circle003.geometry} material={materials['donut back']} />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials['donut glaze']} />
        <mesh geometry={nodes.Circle003_2.geometry} material={materials['donut sprinkles']} />
        <mesh geometry={nodes.Circle003_3.geometry} material={materials['Donut base']} />
      </group>
      <group position={[0, 1.507, 4.791]}>
        <mesh geometry={nodes.Circle004.geometry} material={materials['Auto roos']} />
        <mesh geometry={nodes.Circle004_1.geometry} material={materials['Auto wit']} />
        <mesh geometry={nodes.Circle004_2.geometry} material={materials.Metaal} />
        <mesh geometry={nodes.Circle004_3.geometry} material={materials.spiegels} />
      </group>
      <group position={[-0.981, 3.346, 4.008]} scale={0.624}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.016']} />
      </group>
    </group>
  )
}

useGLTF.preload('/car.glb')
