/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 donut.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import donut from "./assets/donut.glb"
import { RigidBody } from '@react-three/rapier'


export function Donut(props) {
  const { nodes, materials } = useGLTF(donut)
  return (
    <RigidBody colliders={"hull"}>
      <group {...props} dispose={null}>
        <group scale={0.261}>
          <mesh geometry={nodes.Circle003.geometry} material={materials['donut back']} />
          <mesh geometry={nodes.Circle003_1.geometry} material={materials['donut glaze']} />
          <mesh geometry={nodes.Circle003_2.geometry} material={materials['donut sprinkles']} />
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload(donut)
