/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 terrain.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import terrain from "./assets/terrain.glb"

export function Terrain(props) {
  const { nodes, materials } = useGLTF(terrain)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Grass} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.Tops} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials.Mountains} />
      <mesh geometry={nodes.Plane_4.geometry} material={materials.Water} />
      <mesh geometry={nodes.Plane_5.geometry} material={materials.Pavement} />
    </group>
  )
}

useGLTF.preload(terrain)
